version: '3.8'
services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
        NGROK_AUTHTOKEN: ${NGROK_TOKEN}
    command:
        - "start"
        - "dev"
        - "--config"
        - "/etc/ngrok.yml"
    volumes:
        - ${HOME_DIR}/.config/ngrok/ngrok.yml:/etc/ngrok.yml
    networks:
        - internal
    ports:
        - "4040:4040"
  app:
    build:
      context: docker/php/
      dockerfile: Dockerfile
      # убрать и тут и в докерфайле
      args:
          user: bot
          uid: 1000
    image: patriots-vk-bot
    container_name: app
    working_dir: /var/www/patriots-vk-bot
    volumes:
      - ./:/var/www/patriots-vk-bot
    networks:
      - internal
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./:/var/www/patriots-vk-bot
        - ./docker/nginx/:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - internal
    depends_on:
        - app
    restart: unless-stopped
networks:
  internal:
    driver: bridge
